# Generated by Django 6.1.1 on 2026-10-05 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='gameplayer',
            name='unique_game_player_per_user_per_game',
        ),
        migrations.RemoveConstraint(
            model_name='gameplayer',
            name='unique_player_order_per_game',
        ),
        migrations.RemoveConstraint(
            model_name='roundanswer',
            name='unique_round_answer_per_player',
        ),
        migrations.RemoveConstraint(
            model_name='roundanswer',
            name='roundanswer_not_both_selected_option_and_numeric_value',
        ),
        migrations.RemoveConstraint(
            model_name='round',
            name='round_question_reference_matches_type',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='finished_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='game',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='started_at',
        ),
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('city_capture', 'City capture'), ('battle', 'Battle'), ('capital_attack', 'Capital attack'), ('bonus', 'Bonus')], default='city_capture', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='games.player'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('game',), name='unique_active_round_per_game'),
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roundanswer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='roundanswer',
            name='round',
        ),
        migrations.RemoveField(
            model_name='roundanswer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='round',
            name='choice_question',
        ),
        migrations.RemoveField(
            model_name='round',
            name='numeric_question',
        ),
        migrations.RemoveField(
            model_name='round',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='round',
            name='started_at',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'color'), name='unique_color_per_game'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='player_score_gte_0'),
        ),
        migrations.DeleteModel(
            name='GamePlayer',
        ),
        migrations.DeleteModel(
            name='RoundAnswer',
        ),
    ]
